enum actionTypes {
  INSTALL_MINES = 'INSTALL_MINES',
  OPEN_CELLS = 'OPEN_CELLS',
  CHANGE_STAGE = 'CHANGE_STAGE',
  SHOW_MINES = 'SHOW_MINES',
  BLOW_UP_CELL = 'BLOW_UP_CELL',
  TOGGLE_FLAG = 'TOGGLE_FLAG',
  REMOVE_FLAGS = 'REMOVE_FLAGS',
  RECREATE_BOARD = 'RECREATE_BOARD',
  RESTART = 'RESTART',
  SET_FLAGS_REMAINIG = 'SET_FLAGS_REMAINING',
  CHANGE_SETTINGS = 'CHANGE_SETTINGS'
}

export default actionTypes;